# Generated by Django 4.0.1 on 2022-02-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Актеры и режисеры', 'verbose_name_plural': 'Актеры и режисеры'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'звезда рейтинга', 'verbose_name_plural': 'звезда рейтинга'},
        ),
    ]
